### PR TITLE
Use "cryptography" package instead of the OpenSSL command line tool

### LINKED ISSUE #198: Document that openssl need to be on the path for trytls localhost tests to work
Currently the `trytls` tool does print an error on launch if there is no `openssl` on the path, but it would be better to tell it clearly beforehand.

Thanks to @jrave for pointing this out in #196.

### PR DESCRIPTION
**Pull request by jviide**
Generate localhost test certs with the [`cryptography`](https://cryptography.io/) package instead of using the OpenSSL command line tool. As a consequence the code no more prints the OpenSSL version and doesn't check if the OpenSSL tool is in the path.

~~Another tangential change: The localhost HTTPS server is now run in a separate thread instead of a separate process. This enables passing a customized `ssl.SSLContext` to `http_server`, which can be used in the future to implement e.g. SNI tests via `ssl.SSLContext#set_servername_callback`.~~ _Update: Moved the changes mentioned in this paragraph to #261._

Prior to merging the code needs to be tested at least on Windows, OSX and a common Linux distribution of choice. See the [list of platforms `cryptography` supports](https://cryptography.io/en/latest/installation/#supported-platforms). @oherrala might be interested to check out whether this version of `trytls` can still be run on OpenBSD.

Closes #198.

### CODE REVIEW

**Comment by ikisusi** [comment]
OSX 10.10

```
trytls https python stubs/python2-urllib2/run.py 
platform: OS X 10.10.5
runner: trytls 0.3.4 (CPython 2.7.10)
stub: python stubs/python2-urllib2/run.py
 PASS protect against Apple's TLS vulnerability CVE-2014-1266 [reject www.ssllabs.com:10443]
 PASS protect against the FREAK attack [reject www.ssllabs.com:10444]
 FAIL protect against the Logjam attack [reject www.ssllabs.com:10445]
 PASS protect against FREAK attack (test server 1) [reject cve.freakattack.com:443]
 PASS protect against FREAK attack (test server 2) [reject cve2.freakattack.com:443]
 PASS protection against POODLE attack [reject sslv3.dshield.org:443]
 PASS support for TLS server name indication (SNI) [accept badssl.com:443]
 PASS self-signed certificate [reject self-signed.badssl.com:443]
 PASS expired certificate [reject expired.badssl.com:443]
 PASS wrong hostname in certificate [reject wrong.host.badssl.com:443]
 PASS SHA-256 signature [accept sha256.badssl.com:443]
 PASS 1000 subjectAltNames [accept 1000-sans.badssl.com:443]
 FAIL incomplete chain of trust [reject incomplete-chain.badssl.com:443]
 PASS Superfish CA [reject superfish.badssl.com:443]
 PASS eDellRoot CA [reject edellroot.badssl.com:443]
 PASS DSDTestProvider CA [reject dsdtestprovider.badssl.com:443]
 PASS support for TLS server name indication (SNI) #2 [accept tlsfun.de:443]
 PASS expired + self-signed certificate [reject expired.tlsfun.de:443]
 PASS eDellRoot CA #2 [reject badcert-edell.tlsfun.de:443]
 PASS Superfish CA #2 [reject superfish.tlsfun.de:443]
 PASS valid certificate Common Name [accept domain-match.badtls.io:10000]
 PASS valid wildcard certificate Common Name [accept wildcard-match.badtls.io:10001]
 PASS support for Subject Alternative Name (SAN) [accept san-match.badtls.io:10002]
 PASS TLS handshake with 1024 bit Diffie-Hellman (DH) [accept dh1024.badtls.io:10005]
 PASS certificate expired in year 1963 [reject expired-1963.badtls.io:11000]
 PASS certificate validity starts in future [reject future.badtls.io:11001]
 PASS mismatch in certificate's Common Name [reject domain-mismatch.badtls.io:11002]
 PASS Subject Alternative Name (SAN) mismatch [reject san-mismatch.badtls.io:11003]
 PASS certificate has invalid key usage for HTTPS connection [reject bad-key-usage.badtls.io:11005]
 PASS expired certificate [reject expired.badtls.io:11006]
 PASS invalid wildcard certificate Common Name [reject wildcard.mismatch.badtls.io:11007]
 PASS denies use of RC4 ciphers (RFC7465) [reject rc4.badtls.io:11008]
 FAIL denies use of MD5 signature algorithm (RFC6151) [reject weak-sig.badtls.io:11004]
 PASS denies use of RC4 with MD5 ciphers [reject rc4-md5.badtls.io:11009]
Traceback (most recent call last):
  File "/Users/fenris/Library/Python/2.7/bin/trytls", line 9, in <module>
    load_entry_point('trytls==0.3.4', 'console_scripts', 'trytls')()
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/runner.py", line 268, in main
    if not run(command, bundle):
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/runner.py", line 225, in run
    for test, res in testenv.run(tests, collect, args):
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/testenv.py", line 26, in run
    value = stack[-1].send(result)
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/bundles/https.py", line 169, in local
    certdata, keydata, cadata = gencert(cn)
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/gencert.py", line 71, in gencert
    ca_key = _load_private_key(_ca_key())
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/utils.py", line 84, in _memoized
    value.append(func())
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/trytls/gencert.py", line 40, in _gen_key
    backend=default_backend()
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/Users/fenris/Library/Python/2.7/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'
```

**Comment by jviide** [comment]
Updated the pull request by separating `http_server` changes - that were unrelated to using `cryptography` - into their own pull request #261.

**Comment by jviide** [comment]
#262 is an alternative implementation that uses the `oscrypto` and `certbuilder` packages instead of `cryptography`.

**Comment by oherrala** [comment]
Tested to work with OpenBSD-current (almost-6.0). Code looks good to me.

**Comment by jviide** [comment]
Rebased on top of master.

**Comment by oherrala** [comment]
We (@oherrala and @jviide) decided to go with oscrypto + certbuilder  (#262) instead of cryptography package. Closing this as not needed.
