### ISSUE TITLE
python2-urllib2 cannot use cafile in ubuntu-14.04

### ISSUE THREAD

**Issue by Mamietti** [ouspg/trytls#218]
```
# trytls https python python2-urllib2/run.py
platform: Linux (Ubuntu 14.04)
runner: trytls 0.3.0 (CPython 2.7.6, OpenSSL 1.0.1f)
stub: python python2-urllib2/run.py
ERROR valid certificate Common Name [accept domain-match.badtls.io:10000]
      reason: stub exited with return code 1
      output: Traceback (most recent call last):
                File "python2-urllib2/run.py", line 13, in <module>
                  urllib2.urlopen("https://" + host + ":" + port, cafile=cafile)
              TypeError: urlopen() got an unexpected keyword argument 'cafile'
```

**Comment by Mamietti** [comment]
Welp, this requires things implemented in Python 2.7.9.

**Comment by ikisusi** [comment]
Works on python 2.7.5 in CentOS 7.

**Comment by Mamietti** [comment]
@ikisusi might be a backport?

**Comment by aleksiklasila** [comment]
closed by #237
